### ISSUE TITLE
Latest fastcore/fastai breaks blurr

### ISSUE THREAD

**Issue by HenryDashwood** [ohmeow/blurr#10]
Hi Wayde! 

I came across this error today when running this line of code. 
```python
hf_batch_tfm = HF_SummarizationBatchTransform(hf_arch, hf_tokenizer)
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
 in 
----> 1 hf_batch_tfm = HF_SummarizationBatchTransform(hf_arch, hf_tokenizer)

~/projects/fastcore/fastcore/transform.py in __call__(cls, *args, **kwargs)
     36             getattr(cls,n).add(f)
     37             return f
---> 38         return super().__call__(*args, **kwargs)
     39 
     40     @classmethod

~/projects/blurr/blurr/data/summarization.py in __init__(self, hf_arch, hf_tokenizer, **kwargs)
     20 class HF_SummarizationBatchTransform(HF_BatchTransform):
     21     def __init__(self, hf_arch, hf_tokenizer, **kwargs):
---> 22         super().__init__(hf_arch, hf_tokenizer, HF_SummarizationInput, **kwargs)
     23 
     24     def encodes(self, samples):

~/projects/blurr/blurr/data/core.py in __init__(self, hf_arch, hf_tokenizer, hf_input_return_type, **kwargs)
     57     """
     58     def __init__(self, hf_arch, hf_tokenizer, hf_input_return_type=HF_BaseInput, **kwargs):
---> 59         store_attr(self, 'hf_arch, hf_tokenizer, hf_input_return_type, kwargs')
     60 
     61     def encodes(self, samples): return samples

~/projects/fastcore/fastcore/utils.py in store_attr(names, self, but, **attrs)
     95     args,varargs,keyw,locs = inspect.getargvalues(fr)
     96     if self is None: self = locs[args[0]]
---> 97     if not hasattr(self, '__stored_args__'): self.__stored_args__ = {}
     98     if attrs: return _store_attr(self, **attrs)
     99 

AttributeError: 'str' object has no attribute '__stored_args__'
```
This code works with  fastai 2.0.6 and fastcore 1.0.0. I still get quite lost reading all Jeremy's fastcore code (planning to go through Hamel Husain's blog about it soon!) but I came across this diff from yesterday which might be where the problem was introduced.

https://github.com/fastai/fastcore/commit/ea1c33f1c3543e6e4403b1d3b7702a98471f3515#diff-2d5ca7a202ff50e2df29f58cfa4a4c12

**Comment by HenryDashwood** [comment]
You can see an example of this in the CI details of https://github.com/ohmeow/blurr/pull/11

**Comment by bogdansalyp** [comment]
Encountered with the same bug. Parameters call is swapped for the `store_attr` function.

Here's the call:
```
class HF_BatchTransform(Transform):
    """Handles everything you need to assemble a mini-batch of inputs and targets, as well as decode
    HF_TokenizerTransform inputs
    """
    def __init__(self, hf_arch, hf_tokenizer, hf_input_return_type=HF_BaseInput, **kwargs):
        store_attr(self, 'hf_arch, hf_tokenizer, hf_input_return_type, kwargs')
```

Here's the implementation of `store_attr` func in a fastcore lib:
```
def store_attr(names=None, self=None, but=None, **attrs):
    "Store params named in comma-separated `names` from calling context into attrs in `self`"
    fr = inspect.currentframe().f_back
    args,varargs,keyw,locs = inspect.getargvalues(fr)
    if self is None: self = locs[args[0]]
    if not hasattr(self, '__stored_args__'): self.__stored_args__ = {}
    if attrs: return _store_attr(self, **attrs)

    ns = re.split(', *', names) if names else args[1:]
    _store_attr(self, **{n:fr.f_locals[n] for n in ns if n not in L(but)})
```

**Comment by JiGGie145** [comment]
Faced the same thing. Have spent the past hour crawling through the library and swapping the the parameters into the right place. But, honestly I think the error(or at least bad convention) is on the fastcore side, `self` makes more intuitive sense as the first argument. Are you planning to do the swap in your library?

**Comment by bogdansalyp** [comment]
> Faced the same thing. Have spent the past hour crawling through the library and swapping the the parameters into the right place. But, honestly I think the error(or at least bad convention) is on the fastcore side, `self` makes more intuitive sense as the first argument. Are you planning to do the swap in your library?

Please check out the PR I created, naming parameters is a working solution (checked locally)

**Comment by ohmeow** [comment]
I'll be looking at the PRs today and updating accordingly.  Thanks for bringing this to my attention ... I had a feeling with all the chatter about fastcore recently things might break :).  Will let ya'll know when things are good to go.
